Move connectionstring to config
schlechtOptimiziert/PFAX422A-AppProjekt pull request #1
Opened 2023-10-21 12:53 UTC by schlechtOptimiziert

2023-10-22 15:37 UTC, olr-fh commented
Bitte wie erwähnt ReadMe für das Setup hinzufügen. Braucht man neben der Config Datei dann noch eine vorher erstelle Datenbank oder funktioniert das irgendwie automatisch?

2023-10-22 17:47 UTC, schlechtOptimiziert commented
> Bitte wie erwähnt ReadMe für das Setup hinzufügen. Braucht man neben der Config Datei dann noch eine vorher erstelle Datenbank oder funktioniert das irgendwie automatisch?

Ok. Schreibe das alles in die ReadMe. Prinzipiell muss man aber:
DB erstellen => ConnString in die Config und einmal ein update auf die DB machen.

2023-10-22 19:35 UTC, olr-fh commented
Bei den Migrations ist irgendwas nicht richtig gelaufen, bitte einmal AppProjectDbContextModelSnapshot löschen und `dotnet ef migrations add InitialCreate` ausführen. In der entstandenen Migration sollte in Up dann drin stehen, dass ein Table für Item erstellt wird. Die Migration muss commited werden und mit in diesen PR.

2023-10-23 07:59 UTC, olr-fh requested changes

2023-10-23 08:07 UTC, olr-fh approved these changes
LGTM

2023-10-23 11:24 UTC, Amgum approved these changes

2023-10-23 11:30 UTC, rom-fh approved these changes

2023-10-23 11:30 UTC, rom-fh commented on README.md
> +>2. Updaten der DB mit gegebenen migraionen<br/>
Rechtschreibung Blyad 🗿

2023-10-23 11:35 UTC, olr-fh approved these changes
LGTM

2023-10-23 11:40 UTC, Amgum approved these changes

2023-10-23 11:41 UTC, olr-fh approved these changes
2tes review?

2023-10-23 11:49 UTC, merged