Item Details auf der Homepage anzeigen
schlechtOptimiziert/PFAX422A-AppProjekt pull request #10
Opened 2023-11-13 08:46 UTC by Amgum

2023-11-13 09:54 UTC, Amgum commented on MobileClient/Client/Components/HorizontalProductScroller.razor
> +            @if (item.CoverPic != null)
Wird als firstordefault gesetzt, kann ich die Überprüfung sein lassen?!

2023-11-13 10:01 UTC, schlechtOptimiziert requested changes
Yeeeeee

2023-11-13 10:01 UTC, schlechtOptimiziert commented on MobileClient/Client/Pages/Homepage.razor.cs
> +            item.Pictures = await GetItemPicturesAsync(item.Id).ConfigureAwait(false);
Wir sollten vlt eine Methode Server seitig bereitstellen, der das CoverPic direkt zurück gibt. Das wäre in dem Falle Performanter.

2023-11-13 10:04 UTC, schlechtOptimiziert commented on MobileClient/Client/Components/HorizontalProductScroller.razor
> +            @if (item.CoverPic != null)
Sollte man drin lassen. Schadet ja nicht.

2023-11-19 12:35 UTC, schlechtOptimiziert commented on MobileClient/Client/Components/HorizontalProductScroller.razor.cs
> +
Remove empty line

2023-11-19 12:36 UTC, closed without merging