Features/add cart
schlechtOptimiziert/PFAX422A-AppProjekt pull request #17
Opened 2023-11-20 20:33 UTC by olr-fh

2023-11-20 21:27 UTC, schlechtOptimiziert requested changes
Reviewed from Doofenshmirtz evil incorporated >:)

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Client/Pages/ItemDetails.razor.cs
> +    public AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;
Wie oben schon gesagt. In die BaseComponent würde helfen.

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Client/Pages/ItemDetails.razor.cs
> +            await Service.AddItemToCartAsync(userId, itemId, cancellationToken);
Toast oder Fehler? Sollte ja nicht auftreten. Der Nutzer sollte das wissen. Den Fehler zu verschlucken ist da wahrscheinlich nicht so nice.

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Server/Controllers/CartsController.cs
> +    [HttpDelete("{userId}/{itemId}")]
```suggestion
    [HttpDelete("{userId}/Items/{itemId}")]
```

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Server/Controllers/CartsController.cs
> +    [HttpPut("{userId}")]
```suggestion
    [HttpPut("{userId}/Items/{itemId}")]
```

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Server/Controllers/CartsController.cs
> +    [HttpGet("{userId}")]
```suggestion
    [HttpGet("{userId}/Items")]
```

2023-11-20 21:27 UTC, schlechtOptimiziert commented on MobileClient/Server/Controllers/CartsController.cs
> +    [HttpPost("{userId}")]
```suggestion
    [HttpPost("{userId}/Items")]
```
Das macht so mehr Sinn, da du in der menge der Carts eins hast und das eine Menge an Items.

2023-11-20 21:27 UTC, schlechtOptimiziert commented on Shared/DatabaseDefintion/EntityModel/Database/CartItemLink.cs
> +    //[DeleteBehavior(DeleteBehavior.NoAction)]
Ran oder weg. Macht das nen Unterschied? Hast du das getestet?

2023-11-20 21:27 UTC, schlechtOptimiziert commented on Shared/DatabaseDefintion/EntityModel/Repositories/CartRepository.cs
> +        _ = await dbContext.Items.Select(ItemMappings.MapItem)
Gedanken dazu, wir haben das ja immer wieder. Sollten wir in den Entsprechenden Mappings Klassen das einmal statisch definieren? Also einmal für jede Tabelle wo wir das immer überprüfen.
Oder wir machen ein RepositoryHelper.
Oder wir benennen die Mappings in [name]Helper um. (bin ich glaube am meisten Fan von)

2023-11-20 21:27 UTC, schlechtOptimiziert commented on Shared/DatabaseDefintion/EntityModel/Repositories/CartRepository.cs
> +            cartItemLink.Item = await dbContext.Items.Select(ItemMappings.MapItem)
Kann man mit einem .Include lösen. Aber ich bin mir über die reichte Umsetzung mit dem Übertragen von item in TM.Item auch noch nicht im klaren. Sollten wir auf jeden Fall mal die Köpfe zusammenstecken und eine gute Lösung finden. Ich werde das Problem beim Platfrom Dingen auch haben.

2023-11-20 21:27 UTC, schlechtOptimiziert commented on Shared/ServerDataProvider/Service.Item.cs
> +public partial class Service : ICartService
Bitte rückgängig machen. Gehe davon aus, dass das nicht beabsichtigt war.

2023-11-20 21:27 UTC, schlechtOptimiziert commented on Test/DatabaseDefinition.Test/DatabaseDefinitionTestBase.cs
> +        return DbContext.Users.FirstOrDefault() ??
FirstOrDefault macht da nicht so Sinn. Würde Last nicht besser sein? Weil das ja der letzt created ist. Auch wenn das natürlich nicht sicherstellt, dass auch der richtige zurückkommt.

2023-11-21 11:32 UTC, olr-fh commented on MobileClient/Client/Pages/CartPage.razor
> +                    <MudButton ButtonType="ButtonType.Button" Variant="Variant.Text" Style="background-color:var(--lightGreen); width:90%;"> To payment</MudButton>
Müsste die Css-Klasse dann irgendwo anlegen wo die MudButton Komponente darauf zugreifen kann, deswegen finde ich das in einem Style besser

2023-11-21 14:15 UTC, schlechtOptimiziert approved these changes
LGTM

2023-11-21 14:36 UTC, merged