Add platform filter
schlechtOptimiziert/PFAX422A-AppProjekt pull request #21
Opened 2023-11-25 20:59 UTC by schlechtOptimiziert

2023-11-25 21:01 UTC, schlechtOptimiziert reviewed
Self review

2023-11-25 21:01 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +
```suggestion
```

2023-11-25 21:01 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/PlatformDetails.razor.cs
> +
```suggestion
```

2023-11-25 21:01 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/PlatformDetails.razor.cs
> +    }
```suggestion
    }
    
```

2023-11-26 16:21 UTC, olr-fh commented
Kann man einem Spiel mehrere Platformen zuordnen? Bei mir geht das nicht

2023-11-26 16:23 UTC, olr-fh commented
Finde es allgemein bisschen komisch, dass man im Admincenter beim erstellen der Platform die Namen der Bilder kennen muss damit die Bilder angezeigt werden, mir fällt aber auch kein besserer Weg ein das zu lösen. Es bringt aber halt nichts das dynamisch anpassen zu können wenn dadurch das Bild nicht mehr funktioniert :D

2023-11-26 16:23 UTC, olr-fh commented
> Finde es allgemein bisschen komisch, dass man im Admincenter beim erstellen der Platform die Namen der Bilder kennen muss damit die Bilder angezeigt werden, mir fällt aber auch kein besserer Weg ein das zu lösen. Es bringt aber halt nichts das dynamisch anpassen zu können wenn dadurch das Bild nicht mehr funktioniert :D

2023-11-26 16:33 UTC, schlechtOptimiziert commented
> Kann man einem Spiel mehrere Platformen zuordnen? Bei mir geht das nicht

Bei mir geht das.

2023-11-26 16:34 UTC, schlechtOptimiziert commented
> Finde es allgemein bisschen komisch, dass man im Admincenter beim erstellen der Platform die Namen der Bilder kennen muss damit die Bilder angezeigt werden, mir fällt aber auch kein besserer Weg ein das zu lösen. Es bringt aber halt nichts das dynamisch anpassen zu können wenn dadurch das Bild nicht mehr funktioniert :D

Mir fällt da schon ein Weg ein. Man müsste "einfach" den Pfad an die Platform machen. Aber das ist mir zu blöd.

2023-11-26 16:43 UTC, olr-fh requested changes
nicht super genau drübergeguckt

2023-11-26 16:43 UTC, olr-fh commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
Wofür machst du das? Du benutzt das auch gar nicht.

2023-11-26 16:43 UTC, olr-fh commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
Gleiches wie gerade

2023-11-26 16:43 UTC, olr-fh commented on MobileClient/Client/Pages/ProductListPage.razor.cs
> -        NavigationManager.TryGetQueryString("searchText", out searchText);
der searchText muss immer noch aus der Query genommen werden

2023-11-26 16:43 UTC, olr-fh commented on MobileClient/Client/Components/SearchBar.razor.cs
> +        //platform = PlatformExtensions.GetPlatformFromUri(NavigationManager);
Hier muss die Platform id geholt werden, damit sowohl der Platform Filter als auch Suchfilter gleichzeitig benutzt werden können.
Jetzt gerade kann nur ein Filter gleichzeitig genutzt werden.

2023-11-26 16:43 UTC, olr-fh commented on Test/DatabaseDefinition.Test/DatabaseDefinition.Test.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
?

2023-11-26 16:53 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
Doch

2023-11-26 16:53 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
Doch

2023-11-26 16:53 UTC, schlechtOptimiziert commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
Nutze ich!

2023-11-26 16:55 UTC, schlechtOptimiziert commented on Test/DatabaseDefinition.Test/DatabaseDefinition.Test.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Kein Plan was da gemacht wurde.

2023-11-26 17:48 UTC, olr-fh commented on AdminClient/Client/Pages/ItemDetails.razor.cs
> +        await GetPlatformsAsync().ConfigureAwait(false);
wollte hier auf das "await GetPlatformsAsync()..." raus das am Ende der Methode gemacht wird.

2023-11-26 18:34 UTC, olr-fh commented
> > Kann man einem Spiel mehrere Platformen zuordnen? Bei mir geht das nicht
> 
> Bei mir geht das.

Hab herausgefunden warum es nicht ging, wenn man eine Platform z.B. test benennt, dann kriegt man ein 500 zurück wenn man versucht diese einem Spiel zuzuordnen

2023-11-26 20:06 UTC, olr-fh commented on Shared/DatabaseDefintion/Migrations/20231126190850_FixItemFK.cs
Kannst du aus den 2 Migrations eine machen? Also die beiden neuen löschen und eine neue anlegen?

2023-11-26 20:52 UTC, olr-fh approved these changes

2023-11-26 20:55 UTC, merged