Features/add item pictures
schlechtOptimiziert/PFAX422A-AppProjekt pull request #7
Opened 2023-11-03 13:08 UTC by schlechtOptimiziert

2023-11-03 13:33 UTC, olr-fh commented on AppProject/AdminClient/Helper.cs
Klassenname vielleicht eher PictureConverter oder so etwas in der Art?

2023-11-03 14:36 UTC, rom-fh commented on AppProject/AdminClient/Pages/ItemDetails.razor
> +        <MudImage Src="@Helper.ItemPictureToUri(picture)" Width="200" Height="150" Alt="Swedish Farm House" Elevation="25" Class="rounded-lg ma-4" />
Sweet little swedish farm house

2023-11-04 14:12 UTC, olr-fh commented on AppProject/Server/Controllers/ItemPicturesController.cs
> +        Console.WriteLine("Test");
```suggestion
```

2023-11-04 14:18 UTC, olr-fh commented on AppProject/AdminClient/Pages/ItemDetails.razor
> +@if (Id != null)
Wollen wir im Admincenter auch ein ConditionComponent hinzufügen? Damit es einheitlich zwischen Admincenter und Client ist.

2023-11-04 15:03 UTC, olr-fh requested changes

2023-11-04 15:03 UTC, olr-fh commented on AppProject/Server/EntityModel/Repositories/Interfaces/IItemPictureRepository.cs
Löschen wäre noch gut. Vom Admincenter aus.

2023-11-04 17:57 UTC, schlechtOptimiziert commented on AppProject/AdminClient/PictureConverter.cs
> +        byte[] buffer = new byte[2097152];
Die Nummer kommt aus dem Tutorial, wo ich die Logik her habe. Wenn ich raten müsste, dann hängt das mit der max size von Bildern ab, die man in der DB speichern kann.

2023-11-04 20:42 UTC, olr-fh commented
Gibt es vom MudCarousel einen einfachen Weg, dass wenn nur ein Bild existiert die carousel Funktionen deaktiviert werden? Wenn nicht dann lassen wirs erstmal so.

2023-11-05 11:56 UTC, olr-fh approved these changes

2023-11-05 13:32 UTC, merged